services:
  web:
    image: php:8.2-apache
    container_name: php-apache-${DB_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:  
      - ./:/var/www
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.mysql
    container_name: mysql-db-${DB_NAME}
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-${DB_NAME}
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 64M 
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: